worker_processes 1;

events { worker_connections 1024; }

http {
    error_log "C:/nginx/logs/error.log";
    access_log "C:/nginx/logs/access.log";

    upstream laravel_servers {
        least_conn;
        server 127.0.0.1:8001;
        server 127.0.0.1:8002;
        server 127.0.0.1:8003;
    }

    server {
        listen 8080;

        location /nginx_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            deny all;
        }

        location / {
            proxy_pass http://laravel_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
